# 接続設定ファイル
# 参考: [2021年CGFオープン 大会要項](https://hp.vector.co.jp/authors/VA012620/cgf2021/cgf2021.html)

# `Server` - 接続先の情報
[Server]

Host = 'yss-aya.com'

# 接続先サーバーのポート番号
# (^q^) 数値型のデータをクォーテーションで囲むとエラーもなく読取失敗するから注意☆
Port = 9696

# `User` - gtp-engine-to-nngs が利用する区画。人間プレイヤー、GTPエンジン、閲覧者など接続者側の情報など。
[User]

# * `Human` - 人間プレイヤーが接続する
# * `GTP` - GTP(碁テキスト プロトコル)を用いる思考エンジンが接続する
InterfaceType = 'GTP'

# EngineCommand - 思考エンジンを起動するコマンドの実行ファイル名の部分（OSにより書き方が異なるかも）
EngineCommand = 'C:\GitHub\kifuwarabe-go-cpp\cgfopen2021-day1-round1\Release\go15.exe'

# EngineCommandOption - 思考エンジンを起動するコマンドの半角スペース区切りの引数（OSにより書き方が異なるかも）
EngineCommandOption = ''

# `MatchApplication` - gtp-engine-to-nngs が利用する区画。マッチの申込の挙動
[MatchApplication]

# 申し込みません
ApplyFromMe = false

# 無視します
OpponentName = ""

# 白番なら 'W', 黒番なら 'B'
Phase = 'W'

# 何路盤
BoardSize = 9

# 持ち時間（分）
AvailableTimeMinutes = 10

# カナダ式秒読み。25手を何分以内に打てばよいか
CanadianTiming = 0
